export const SET_MY_POKEMON = "MY_POKEMON/DATA";
export const SET_MY_POKEMON_ERROR = "MY_POKEMON/ERROR";
export const SET_MY_POKEMON_LOADING = "MY_POKEMON/LOADING";
export const SET_MY_POKEMON_SELECTED = "MY_POKEMON/SELECTED";