export const SET_POKEMON = "POKEMON/DATA";
export const SET_POKEMON_ERROR = "POKEMON/ERROR";
export const SET_POKEMON_LOADING = "POKEMON/LOADING";
export const SET_POKEMON_SELECTED = "POKEMON/SELECTED";